# This workflow will delete packages of feature and bugfix branches

name: Delete old packages
permissions:
  packages: write
on:
  workflow_dispatch:
jobs:
  delete_packages:
    runs-on: ubuntu-latest
    steps:
    - name: Delete insign-rest-api-nodep
      uses: actions/delete-package-versions@v5
      with:
        package-name: 'de.is2.insign.insign-rest-api-nodep'
        package-type: 'maven'
        num-old-versions-to-delete: 1000
        ignore-versions: '3\.[0-9]+\.[0-9]+$'
    - name: Delete insign-java-api
      uses: actions/delete-package-versions@v5
      with:
        package-name: 'de.is2.insign.insign-java-api'
        package-type: 'maven'
        num-old-versions-to-delete: 1000
        ignore-versions: '3\.[0-9]+\.[0-9]+$'
    - name: Delete insign-parent
      uses: actions/delete-package-versions@v5
      with:
        package-name: 'de.is2.insign.insign-parent'
        package-type: 'maven'
        num-old-versions-to-delete: 1000
        ignore-versions: '3\.[0-9]+\.[0-9]+$'
