# This workflow will delete packages of feature and bugfix branches

name: Delete old packages

on:
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/delete-package-versions@v5
    - name: Delete insign-rest-api-nodep
      with:
        package-name: 'de.is2.insign.insign-rest-api-nodep'
        package-type: 'maven'
        num-old-versions-to-delete: 1
        ignore-versions: '3\.[0-9]+\.[0-9]+$'
